// LS RANDULA   170502G

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaMaths;
import javax.swing.JOptionPane;

/**
 *
 * @author LS RANDULA
 */
public class Calculator extends javax.swing.JFrame {  //Contains GUI + main method
    
    private double number1;
    private double number2;
    private double number3; // for trigonometric, logarithmic and exponential calculations 
    private int number4; // for factorials
    private String operation;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScreen1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonEqualSign = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonSubstract = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonSin = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButton10toX = new javax.swing.JButton();
        jButtonXtoY = new javax.swing.JButton();
        jButtonEtoX = new javax.swing.JButton();
        jButtonLn = new javax.swing.JButton();
        jButtonSqrt = new javax.swing.JButton();
        jButtonLog10 = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonFactX = new javax.swing.JButton();
        jButtonPi = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonNegative = new javax.swing.JButton();
        jButtonDecimal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");

        jScreen1.setBackground(new java.awt.Color(204, 204, 204));
        jScreen1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jScreen1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jScreen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScreen1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButtonEqualSign.setBackground(new java.awt.Color(255, 255, 153));
        jButtonEqualSign.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonEqualSign.setText("=");
        jButtonEqualSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualSignActionPerformed(evt);
            }
        });

        jButton0.setBackground(new java.awt.Color(204, 255, 255));
        jButton0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonAdd.setBackground(new java.awt.Color(204, 204, 255));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonSubstract.setBackground(new java.awt.Color(204, 204, 255));
        jButtonSubstract.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonSubstract.setText("-");
        jButtonSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstractActionPerformed(evt);
            }
        });

        jButtonMultiply.setBackground(new java.awt.Color(204, 204, 255));
        jButtonMultiply.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonMultiply.setText("*");
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });

        jButtonDivide.setBackground(new java.awt.Color(204, 204, 255));
        jButtonDivide.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDivide.setText("/");
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });

        jButtonSin.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSin.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonSin.setText("sin()");
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });

        jButtonCos.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCos.setText("cos()");
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });

        jButtonTan.setBackground(new java.awt.Color(204, 255, 204));
        jButtonTan.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonTan.setText("tan()");
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });

        jButton10toX.setBackground(new java.awt.Color(204, 255, 204));
        jButton10toX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10toX.setText("10^x");
        jButton10toX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10toXActionPerformed(evt);
            }
        });

        jButtonXtoY.setBackground(new java.awt.Color(204, 255, 204));
        jButtonXtoY.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonXtoY.setText("x^y");
        jButtonXtoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXtoYActionPerformed(evt);
            }
        });

        jButtonEtoX.setBackground(new java.awt.Color(204, 255, 204));
        jButtonEtoX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonEtoX.setText("e^x");
        jButtonEtoX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEtoXActionPerformed(evt);
            }
        });

        jButtonLn.setBackground(new java.awt.Color(204, 255, 204));
        jButtonLn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLn.setText("ln()");
        jButtonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLnActionPerformed(evt);
            }
        });

        jButtonSqrt.setBackground(new java.awt.Color(204, 255, 204));
        jButtonSqrt.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonSqrt.setText("sq. root");
        jButtonSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSqrtActionPerformed(evt);
            }
        });

        jButtonLog10.setBackground(new java.awt.Color(204, 255, 204));
        jButtonLog10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonLog10.setText("log10");
        jButtonLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLog10ActionPerformed(evt);
            }
        });

        jButtonE.setBackground(new java.awt.Color(204, 255, 204));
        jButtonE.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonE.setText("e");
        jButtonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEActionPerformed(evt);
            }
        });

        jButtonFactX.setBackground(new java.awt.Color(204, 255, 204));
        jButtonFactX.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonFactX.setText("x!");
        jButtonFactX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFactXActionPerformed(evt);
            }
        });

        jButtonPi.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPi.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonPi.setText("pi");
        jButtonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiActionPerformed(evt);
            }
        });

        jButtonC.setBackground(new java.awt.Color(255, 204, 204));
        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonNegative.setBackground(new java.awt.Color(204, 204, 255));
        jButtonNegative.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonNegative.setText("+/-");
        jButtonNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNegativeActionPerformed(evt);
            }
        });

        jButtonDecimal.setBackground(new java.awt.Color(204, 255, 255));
        jButtonDecimal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonDecimal.setText(".");
        jButtonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScreen1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonSubstract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton10toX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonXtoY, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonEtoX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButtonFactX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonEqualSign, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScreen1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(jButtonSubstract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10toX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonXtoY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonEtoX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonFactX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMultiply, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDivide, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNegative, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEqualSign, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numberEntered = jScreen1.getText() + jButton1.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jScreen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScreen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jScreen1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String numberEntered = jScreen1.getText() + jButton3.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String numberEntered = jScreen1.getText() + jButton4.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String numberEntered = jScreen1.getText() + jButton6.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String numberEntered = jScreen1.getText() + jButton7.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String numberEntered = jScreen1.getText() + jButton9.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String numberEntered = jScreen1.getText() + jButton8.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButtonEqualSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualSignActionPerformed
        
        try{
        if(this.operation == "+" | this.operation == "-" | this.operation == "*" | this.operation == "/"){    // Baisc Arithmetic
            this.number2 = Double.parseDouble(jScreen1.getText());

            if (this.operation == "+"){
                //System.out.println(this.number1+this.number2);
                jScreen1.setText(String.format("%.2f", BasicArithmetic.addition(this.number1, this.number2) ));
            }

            else if (this.operation == "-"){
                  jScreen1.setText(String.format("%.2f", BasicArithmetic.substraction(this.number1, this.number2) ));
            }

            else if (this.operation == "*"){
                  jScreen1.setText(String.format("%.2f", BasicArithmetic.multiplication(this.number1, this.number2) ));
            }

            else if (this.operation == "/"){
                  jScreen1.setText(String.format("%.2f", BasicArithmetic.division(this.number1, this.number2) ));
            }
            this.operation = "";
        }
        
        else{
            
            if (this.operation == "sin()"){
                
                this.number3 = Double.parseDouble(jScreen1.getText().substring(47)); // gets the value of x of sin(x)
                jScreen1.setText(String.format("%.2f", Trigonometry.sine(this.number3) ));
                //System.out.println(this.number3);
                this.operation = "";
            }
            
            else if (this.operation == "cos()"){
                
                this.number3 = Double.parseDouble(jScreen1.getText().substring(47)); // gets the value of x of cos(x)
                jScreen1.setText(String.format("%.2f", Trigonometry.cosine(this.number3) ));
                //System.out.println(this.number3);
                this.operation = "";
            }
            
            else if (this.operation == "tan()"){
                
                this.number3 = Double.parseDouble(jScreen1.getText().substring(47)); // gets the value of x of tan(x)
                jScreen1.setText(String.format("%.2f", Trigonometry.tangent(this.number3) ));
                //System.out.println(this.number3);
                this.operation = "";
            }
            
            else if (this.operation== "10toX"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(33)); // gets the value of x of 10^x
                jScreen1.setText(String.format("%.2f", Exponentials.tenToX(this.number3)));
                this.operation = "";
            }
            
            else if (this.operation== "XtoY_X"){
                this.number1 = Double.parseDouble(jScreen1.getText().substring(32)); // gets the value of x of x^y
                this.operation= "XtoY_Y";
                jScreen1.setText("x^y Calculation: Please Enter y=");
                
            }
            
            else if (this.operation== "XtoY_Y"){
                this.number2 = Double.parseDouble(jScreen1.getText().substring(32));    // gets the value of y of x^y
                jScreen1.setText(String.format("%.2f", Exponentials.xToY(this.number1, this.number2)));
                this.operation = "";
            }
            
            else if (this.operation== "EtoX"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(32)); // gets the value of x of e^x
                jScreen1.setText(String.format("%.2f", Exponentials.eToX(this.number3)));
                this.operation = "";
            }
            
            else if (this.operation== "logTen"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(37)); // gets the value of x of lon10(x)
                jScreen1.setText(String.format("%.2f", Logarithms.logTen(this.number3)));
                this.operation = "";
            }
            
            else if (this.operation== "logN"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(34)); // gets the value of x of logN(x)
                jScreen1.setText(String.format("%.2f", Logarithms.logN(this.number3)));
                this.operation = "";
            }
            
            else if (this.operation== "sqRoot"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(45)); // gets the value of x of sqrt(x)
                jScreen1.setText(String.format("%.2f", Exponentials.sqRoot(this.number3)));
                this.operation = "";
            }
            
            else if (this.operation== "factOfX"){
                this.number3 = Double.parseDouble(jScreen1.getText().substring(41)); // gets the value of x of factorial(x)
                this.number4 = (int)this.number3;
                //System.out.println(this.number4);
                if (this.number4<=12){
                    jScreen1.setText(String.format("%d", Factorials.factorialOfX(this.number4)));
                }
                else{
                    JOptionPane.showMessageDialog(null, "<html><font size = '15'>Overflow occured!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
                    jScreen1.setText("");
                }
                
                this.operation = "";
            }
            
            else{
                JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        jButtonAdd.setEnabled(true);
        jButtonSubstract.setEnabled(true);
        jButtonMultiply.setEnabled(true);
        jButtonDivide.setEnabled(true);
        jButtonNegative.setEnabled(true);
        }
        
        catch(NumberFormatException ex){
            //System.out.println("NumberFormatException");   // catches the error which occurs when no input has been entered
            //jScreen1.setText("Please enter a number for x");
            //JOptionPane.showMessageDialog(frame, "Error");
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter a value for x!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch(StackOverflowError ex){
               JOptionPane.showMessageDialog(null, "<html><font size = '15'>Value too large to calculate!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEqualSignActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String numberEntered = jScreen1.getText() + jButton0.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonEtoXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEtoXActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("e^x Calculation: Please Enter x=");
        this.operation = "EtoX";
    }//GEN-LAST:event_jButtonEtoXActionPerformed

    private void jButtonSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSqrtActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("Square Root Calculation of x: Please Enter x=");
        this.operation = "sqRoot";
    }//GEN-LAST:event_jButtonSqrtActionPerformed

    private void jButtonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEActionPerformed
        jScreen1.setText(String.valueOf(Math.exp(1)));
    }//GEN-LAST:event_jButtonEActionPerformed

    private void jButtonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecimalActionPerformed
        String numberEntered = jScreen1.getText() + jButtonDecimal.getText();
        String temp = jScreen1.getText();
        boolean forLoopBroken = false;
        
        for (int i=0; i< temp.length(); i++){
            if (".".equals(Character.toString(temp.charAt(i)))){
                forLoopBroken = true;
                break;      // To limit the user from inputting more tha one "." which would leave to errors
            }
        }
        
        if (forLoopBroken == false){
            jScreen1.setText(numberEntered);
        }   
    }//GEN-LAST:event_jButtonDecimalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String numberEntered = jScreen1.getText() + jButton2.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String numberEntered = jScreen1.getText() + jButton5.getText();
        jScreen1.setText(numberEntered);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jScreen1.setText("");
        jButtonAdd.setEnabled(true);
        jButtonSubstract.setEnabled(true);
        jButtonMultiply.setEnabled(true);
        jButtonDivide.setEnabled(true);
        jButtonNegative.setEnabled(true);
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        try{
            this.number1 = Double.parseDouble(jScreen1.getText());
            jScreen1.setText("");
            this.operation = "+";
        }
        
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstractActionPerformed
        try{
            this.number1 = Double.parseDouble(jScreen1.getText());
            jScreen1.setText("");
            this.operation = "-";
        }
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubstractActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        try{
            this.number1 = Double.parseDouble(jScreen1.getText());
            jScreen1.setText("");
            this.operation = "*";
        }
        
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        try{
            this.number1 = Double.parseDouble(jScreen1.getText());
            jScreen1.setText("");
            this.operation = "/";
        }
        
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNegativeActionPerformed
        try{
            double makeNegative = Double.parseDouble(String.valueOf(jScreen1.getText()));
            makeNegative = makeNegative * (-1);
            jScreen1.setText(String.valueOf(makeNegative));
        }
        
        catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "<html><font size = '15'>Please enter an input!!", " '10'>Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonNegativeActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("sin(x) Calculation: Please Enter x(in radians)=");
        this.operation = "sin()";
        
    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("cos(x) Calculation: Please Enter x(in radians)=");
        this.operation = "cos()";
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("tan(x) Calculation: Please Enter x(in radians)=");
        this.operation = "tan()";
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jButtonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiActionPerformed
        jScreen1.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_jButtonPiActionPerformed

    private void jButton10toXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10toXActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("10^x Calculation: Please Enter x=");
        this.operation = "10toX";
    }//GEN-LAST:event_jButton10toXActionPerformed

    private void jButtonXtoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXtoYActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("x^y Calculation: Please Enter x=");
        this.operation = "XtoY_X";
    }//GEN-LAST:event_jButtonXtoYActionPerformed

    private void jButtonLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLog10ActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("log10(x) Calculation: Please Enter x=");
        this.operation = "logTen";
    }//GEN-LAST:event_jButtonLog10ActionPerformed

    private void jButtonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLnActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("ln(x) Calculation: Please Enter x=");
        this.operation = "logN";
    }//GEN-LAST:event_jButtonLnActionPerformed

    private void jButtonFactXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFactXActionPerformed
        jButtonAdd.setEnabled(false);
        jButtonSubstract.setEnabled(false);
        jButtonMultiply.setEnabled(false);
        jButtonDivide.setEnabled(false);
        jButtonNegative.setEnabled(false);
        jScreen1.setText("Factorial(x) Calculation: Please Enter x=");
        this.operation = "factOfX";
    }//GEN-LAST:event_jButtonFactXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10toX;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonDecimal;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonEqualSign;
    private javax.swing.JButton jButtonEtoX;
    private javax.swing.JButton jButtonFactX;
    private javax.swing.JButton jButtonLn;
    private javax.swing.JButton jButtonLog10;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNegative;
    private javax.swing.JButton jButtonPi;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSqrt;
    private javax.swing.JButton jButtonSubstract;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JButton jButtonXtoY;
    private javax.swing.JTextField jScreen1;
    // End of variables declaration//GEN-END:variables
}


